/**
 * MK. 2 MOVE TABLE.
 *
 * FORM 1 names are engineered techniques (what the stickman Creator designed).
 * FORM 2 names are declarations (what happened after the wrong Creator answered).
 *
 * Every physical spear attack thrusts, stabs, lunges or impales. Mk. 2 does not
 * bonk people with a polearm.
 */

import { ARRAY, CHARGE, F1, JUDGEMENT, PHASE, S1, SPLITTER, STATUS } from './constants';
import type { MoveDef, ShotDef } from '../../sim/types';

const SPEAR = ['spear', 'thrust'];
const LIGHT = ['spear', 'thrust', 'lightning'];

/* ================================================================== */
/* FORM 1 - HEAVEN SPLITTER                                          */
/* ================================================================== */

export const FORM1_MOVES: MoveDef[] = [
  {
    id: F1.flashThrust,
    name: 'FLASH THRUST',
    input: 'J',
    type: 'normal',
    startup: 5,
    active: 3,
    recovery: 9,
    damage: 32,
    chip: 4,
    hitstun: 16,
    blockstun: 12,
    hitstop: 6,
    guardCrush: 7,
    maxHits: 1,
    boxes: [{ x: 16, y: 34, w: 80, h: 20 }],
    vel: [{ from: 5, to: 9, vx: 3.4, vy: 0 }],
    chain: [F1.flashThrust, F1.streakLunge, F1.thunderline],
    cancelOnHit: [
      F1.flashThrust,
      F1.streakLunge,
      F1.railspear,
      F1.railspearL1,
      F1.railspearL2,
      F1.thunderline,
      F1.thunderlineEnhanced,
      F1.heavenfallRise,
    ],
    onHit: 'mk2:flashThrustHit',
    tags: LIGHT,
    fx: 'thrustSmall',
    note: 'Fast confirm. Clean hit: +1 Divine Charge, +1 Conductive. Counter: one more of each.',
  },
  {
    id: F1.streakLunge,
    name: 'STREAK LUNGE',
    input: 'K',
    type: 'normal',
    startup: 9,
    active: 4,
    recovery: 15,
    damage: 46,
    chip: 6,
    hitstun: 18,
    blockstun: 14,
    hitstop: 7,
    guardCrush: 10,
    maxHits: 1,
    boxes: [{ x: 20, y: 32, w: 98, h: 24 }],
    vel: [{ from: 8, to: 14, vx: 7.6, vy: 0 }],
    chain: [F1.flashThrust, F1.streakLunge],
    onActivate: 'mk2:streakLungeStart',
    onHit: 'mk2:streakLungeHit',
    tags: SPEAR,
    fx: 'thrustAdvance',
    note: 'Advancing thrust. 2+ Conductive on target: consume 1 for travel invulnerability. Counter Hit applies Pierced.',
  },
  {
    id: F1.railspear,
    name: 'RAILSPEAR',
    input: 'L (tap)',
    type: 'special',
    startup: 13,
    active: 4,
    recovery: 20,
    damage: 96,
    chip: 12,
    hitstun: 22,
    blockstun: 16,
    hitstop: 10,
    guardCrush: 24,
    maxHits: 1,
    knockdown: true,
    boxes: [{ x: 22, y: 30, w: 104, h: 26 }],
    vel: [{ from: 13, to: 18, vx: 5.4, vy: 0 }],
    chain: [],
    cancelOnHit: [F1.thunderline, F1.heavensArray, F1.splitter1, F1.splitter2, F1.splitter3],
    onHit: 'mk2:railspearHit',
    tags: SPEAR,
    fx: 'railThrust',
    note: 'Committed heavy thrust. Hold L to charge it into a Divine Charge level.',
  },
  {
    id: F1.railspearL1,
    name: 'RAILSPEAR - COMPRESSED',
    input: 'L (hold) · 4 Divine Charge',
    type: 'special',
    startup: 15,
    active: 4,
    recovery: 22,
    damage: 128,
    chip: 16,
    hitstun: 24,
    blockstun: 17,
    hitstop: 12,
    guardCrush: 42,
    maxHits: 1,
    knockdown: true,
    boxes: [{ x: 22, y: 28, w: 116, h: 28 }],
    vel: [{ from: 15, to: 21, vx: 6.6, vy: 0 }],
    cost: { primary: 4 },
    onActivate: 'mk2:railspearL1Start',
    onHit: 'mk2:railspearL1Hit',
    tags: SPEAR,
    fx: 'railThrustCompressed',
    note: 'Heaven Splitter compresses. Pierced + Conductive on hit, huge guard damage. Whiff and the 4 Charge is gone.',
  },
  {
    id: F1.railspearL2,
    name: 'RAILSPEAR - FULL RAIL',
    input: 'L (hold) · 8 Divine Charge',
    type: 'special',
    startup: 19,
    active: 6,
    recovery: 26,
    damage: 176,
    chip: 22,
    hitstun: 28,
    blockstun: 18,
    hitstop: 14,
    guardCrush: 68,
    maxHits: 1,
    knockdown: true,
    boxes: [{ x: 24, y: 26, w: 132, h: 30 }],
    vel: [{ from: 19, to: 27, vx: 8.2, vy: 0 }],
    cost: { primary: 8 },
    onActivate: 'mk2:railspearL2Start',
    onHit: 'mk2:railspearL2Hit',
    tags: SPEAR,
    fx: 'railThrustFull',
    note: 'White-gold rail. Consumes Pierced for extra damage. The Charge is spent whether you connect or not.',
  },
  {
    id: F1.flashPhase,
    name: 'FLASH PHASE',
    input: 'I',
    type: 'movement',
    startup: 3,
    active: 12,
    recovery: 6,
    damage: 0,
    chip: 0,
    hitstun: 0,
    blockstun: 0,
    hitstop: 0,
    guardCrush: 0,
    maxHits: 0,
    boxes: [],
    onActivate: 'mk2:flashPhaseStart',
    onExpire: 'mk2:flashPhaseEnd',
    tags: ['phase'],
    fx: 'phase',
    note: 'Fast displacement with little defensive value. Phase it perfectly to become untouchable.',
  },
  {
    id: F1.heavenfallRise,
    name: 'HEAVENFALL - ASCENT',
    input: 'U',
    type: 'special',
    startup: 10,
    active: 10,
    recovery: 6,
    damage: 68,
    chip: 8,
    hitstun: 20,
    blockstun: 14,
    hitstop: 8,
    guardCrush: 12,
    maxHits: 1,
    boxes: [{ x: 6, y: 60, w: 70, h: 120 }],
    onActivate: 'mk2:heavenfallStart',
    onExpire: 'mk2:heavenfallDrop',
    cost: { primary: 0 },
    tags: LIGHT,
    fx: 'heavenfallRise',
    note: 'Controlled anti-air. Upward spear motion into a descending impalement.',
  },
  {
    id: F1.heavenfallRiseEnhanced,
    name: 'HEAVENFALL - ASCENT (DIVINE)',
    input: 'U \u00b7 6 Divine Charge',
    type: 'special',
    startup: 9,
    active: 10,
    recovery: 6,
    damage: 78,
    chip: 10,
    hitstun: 20,
    blockstun: 14,
    hitstop: 9,
    guardCrush: 14,
    maxHits: 1,
    boxes: [{ x: 6, y: 60, w: 74, h: 130 }],
    cost: { primary: 6 },
    onActivate: 'mk2:heavenfallStart',
    onExpire: 'mk2:heavenfallDrop',
    tags: LIGHT,
    fx: 'heavenfallRiseEnhanced',
    note: 'Divine Charge turns the ascent into a launch. The descent hits far harder.',
  },
  {
    id: F1.heavenfallFall,
    name: 'HEAVENFALL - IMPALEMENT',
    input: 'U (follow up)',
    type: 'special',
    startup: 4,
    active: 12,
    recovery: 18,
    damage: 104,
    chip: 14,
    hitstun: 26,
    blockstun: 16,
    hitstop: 11,
    guardCrush: 20,
    maxHits: 1,
    knockdown: true,
    boxes: [{ x: -6, y: 0, w: 76, h: 120 }],
    guard: 'low',
    vel: [{ from: 4, to: 16, vx: 0, vy: -18 }],
    onActivate: 'mk2:heavenfallFallStart',
    onHit: 'mk2:heavenfallFallHit',
    tags: LIGHT,
    fx: 'heavenfallFall',
    note: 'Conductive amplifies the landing. 3 consumed Conductive locks the target in Static Lock.',
  },
  {
    id: F1.thunderline,
    name: 'THUNDERLINE',
    input: 'O',
    type: 'special',
    startup: 12,
    active: 4,
    recovery: 20,
    damage: 68,
    chip: 9,
    hitstun: 20,
    blockstun: 15,
    hitstop: 8,
    guardCrush: 14,
    maxHits: 1,
    boxes: [{ x: 24, y: 30, w: 150, h: 22 }],
    vel: [{ from: 12, to: 17, vx: 9.5, vy: 0 }],
    chain: [F1.flashThrust, F1.thunderline],
    onHit: 'mk2:thunderlineHit',
    tags: LIGHT,
    fx: 'thunderline',
    note: 'Line-based lightning thrust. Real recovery, real commitment.',
  },
  {
    id: F1.thunderlineEnhanced,
    name: 'THUNDERLINE - ALIGNED',
    input: 'O · 4 Divine Charge · 2+ Conductive or Heaven\'s Mark',
    type: 'special',
    startup: 9,
    active: 4,
    recovery: 16,
    damage: 58,
    chip: 7,
    hitstun: 18,
    blockstun: 14,
    hitstop: 9,
    guardCrush: 18,
    maxHits: 1,
    boxes: [],
    cost: { primary: 4 },
    requires: { targetStacks: { conductive: 1, heavensMark: 1 } },
    onActivate: 'mk2:thunderlineEnhancedStart',
    shot: S1.thunderline,
    shotFrame: 2,
    tags: LIGHT,
    fx: 'thunderlineEnhanced',
    note: 'Aligns Heaven Splitter with the target and fires raw gold lightning through the line. Consumes Conductive, applies Pierced.',
  },
  {
    id: F1.heavensArray,
    name: "HEAVEN'S ARRAY",
    input: 'DOWN + O · 6 Divine Charge',
    type: 'special',
    startup: 16,
    active: 2,
    recovery: 24,
    damage: 0,
    chip: 0,
    hitstun: 0,
    blockstun: 0,
    hitstop: 0,
    guardCrush: 0,
    maxHits: 0,
    boxes: [],
    cost: { primary: ARRAY.cost },
    onActivate: 'mk2:heavensArrayStart',
    onExpire: 'mk2:heavensArrayEnd',
    tags: ['lightning'],
    fx: 'heavensArray',
    note: 'Five cloud-held gold lightning spear lines. 3 connected apply Static Lock. All 5 apply Heaven\'s Mark.',
  },
  {
    id: F1.judgementBolt,
    name: 'JUDGEMENT BOLT',
    input: 'P · 1 Heaven\'s Mark · 5 Divine Charge',
    type: 'special',
    startup: 18,
    active: 2,
    recovery: 26,
    damage: 0,
    chip: 0,
    hitstun: 0,
    blockstun: 0,
    hitstop: 0,
    guardCrush: 0,
    maxHits: 0,
    boxes: [],
    cost: { primary: JUDGEMENT.cost, consume: { heavensMark: JUDGEMENT.markCost } },
    requires: { targetStacks: { heavensMark: 1 }, primary: JUDGEMENT.cost },
    onActivate: 'mk2:judgementBoltStart',
    onExpire: 'mk2:judgementBoltEnd',
    tags: ['divine', 'lightning'],
    fx: 'judgementBolt',
    note: 'No Mark, no Charge: the move does not activate. 1 Mark = one enormous bolt, 3 Marks = three.',
  },
  {
    id: F1.splitter1,
    name: 'HEAVEN SPLITTER: DIVINE EXECUTION (I)',
    input: 'R · 10-14 Divine Charge',
    type: 'super',
    startup: 8,
    active: 1,
    recovery: 96,
    damage: 0,
    chip: 0,
    hitstun: 0,
    blockstun: 0,
    hitstop: 0,
    guardCrush: 0,
    maxHits: 0,
    boxes: [],
    invuln: [1, 9],
    armor: [10, 200],
    cost: { primary: SPLITTER.t1.charge },
    requires: { primary: SPLITTER.min },
    onActivate: 'mk2:splitter1Start',
    tags: ['spear', 'lightning'],
    fx: 'splitter1',
    note: 'Incomplete execution. Four strikes, still strong.',
  },
  {
    id: F1.splitter2,
    name: 'HEAVEN SPLITTER: DIVINE EXECUTION (II)',
    input: 'R · 15-19 Divine Charge',
    type: 'super',
    startup: 8,
    active: 1,
    recovery: 116,
    damage: 0,
    chip: 0,
    hitstun: 0,
    blockstun: 0,
    hitstop: 0,
    guardCrush: 0,
    maxHits: 0,
    boxes: [],
    invuln: [1, 9],
    armor: [10, 260],
    cost: { primary: SPLITTER.t2.charge },
    requires: { primary: SPLITTER.t2.min },
    onActivate: 'mk2:splitter2Start',
    tags: ['spear', 'lightning'],
    fx: 'splitter2',
    note: 'Six strikes and a heavier final thrust. Better status cash out.',
  },
  {
    id: F1.splitter3,
    name: 'HEAVEN SPLITTER: DIVINE EXECUTION (III)',
    input: 'R · 20 Divine Charge',
    type: 'super',
    startup: 8,
    active: 1,
    recovery: 150,
    damage: 0,
    chip: 0,
    hitstun: 0,
    blockstun: 0,
    hitstop: 0,
    guardCrush: 0,
    maxHits: 0,
    boxes: [],
    invuln: [1, 9],
    armor: [10, 320],
    cost: { primary: SPLITTER.t3.charge },
    requires: { primary: SPLITTER.t3.min },
    onActivate: 'mk2:splitter3Start',
    tags: ['spear', 'lightning'],
    fx: 'splitter3',
    note: 'The full execution: nine high-speed repositioning strikes, then one massive thrust.',
  },
  {
    id: F1.splitterEx,
    name: 'HEAVEN SPLITTER: DIVINE EXECUTION (FULL)',
    input: 'R · 20 Divine Charge · Attunement 3 · Marked target',
    type: 'super',
    startup: 8,
    active: 1,
    recovery: 170,
    damage: 0,
    chip: 0,
    hitstun: 0,
    blockstun: 0,
    hitstop: 0,
    guardCrush: 0,
    maxHits: 0,
    boxes: [],
    invuln: [1, 9],
    armor: [10, 360],
    cost: { primary: SPLITTER.ex.charge },
    requires: { primary: SPLITTER.ex.min, tier: SPLITTER.ex.attunement, targetStacks: { heavensMark: 1 } },
    onActivate: 'mk2:splitterExStart',
    tags: ['spear', 'divine', 'lightning'],
    fx: 'splitterEx',
    note: 'Maximum Attunement with maximum setup. This is the cash out.',
  },
  /* strike entities used by the execution sequences */
  {
    id: F1.execStrike,
    name: 'EXECUTION STRIKE',
    input: '-',
    type: 'finisher',
    startup: 1,
    active: 2,
    recovery: 2,
    damage: 64,
    chip: 8,
    hitstun: 14,
    blockstun: 12,
    hitstop: 5,
    guardCrush: 8,
    maxHits: 1,
    boxes: [],
    onHit: 'mk2:execStrikeHit',
    tags: ['spear', 'lightning'],
    fx: 'execStrike',
  },
  {
    id: F1.execStrikeHeavy,
    name: 'EXECUTION STRIKE (HEAVY)',
    input: '-',
    type: 'finisher',
    startup: 1,
    active: 2,
    recovery: 2,
    damage: 92,
    chip: 12,
    hitstun: 18,
    blockstun: 14,
    hitstop: 7,
    guardCrush: 16,
    maxHits: 1,
    boxes: [],
    onHit: 'mk2:execStrikeHit',
    tags: ['spear', 'lightning'],
    fx: 'execStrikeHeavy',
  },
  {
    id: F1.execFinal,
    name: 'HEAVEN SPLITTER - FINAL THRUST',
    input: '-',
    type: 'finisher',
    startup: 1,
    active: 3,
    recovery: 4,
    damage: 150,
    chip: 20,
    hitstun: 30,
    blockstun: 20,
    hitstop: 16,
    guardCrush: 46,
    maxHits: 1,
    knockdown: true,
    boxes: [],
    onHit: 'mk2:execFinalHit',
    tags: ['spear', 'divine', 'lightning'],
    fx: 'execFinal',
  },
];

/* ================================================================== */
/* FORM 1 SHOTS                                                       */
/* ================================================================== */

export const FORM1_SHOTS: ShotDef[] = [
  {
    kind: S1.thunderline,
    speed: 21,
    life: 34,
    damage: 62,
    chip: 8,
    hitstun: 18,
    blockstun: 14,
    hitstop: 8,
    guardCrush: 16,
    box: { x: 0, y: 0, w: 132, h: 26 },
    rehit: 0,
    onHit: 'mk2:thunderlineShotHit',
    tags: ['spear', 'thrust', 'lightning'],
    fx: 'thunderlineLine',
  },
  {
    kind: S1.arraySpear,
    speed: 12.5,
    life: 74,
    damage: ARRAY.damage,
    chip: 5,
    hitstun: 16,
    blockstun: 13,
    hitstop: 6,
    guardCrush: 7,
    box: { x: 0, y: 0, w: 116, h: 34 },
    rehit: 0,
    onHit: 'mk2:arraySpearHit',
    tags: ['lightning', 'spear', 'thrust'],
    fx: 'arraySpear',
  },
  {
    kind: S1.judgement,
    speed: 15.5,
    life: 90,
    damage: JUDGEMENT.damage[0],
    chip: 26,
    hitstun: 24,
    blockstun: 18,
    hitstop: 14,
    guardCrush: 40,
    box: { x: 0, y: 0, w: 104, h: 120 },
    rehit: 0,
    onHit: 'mk2:judgementShotHit',
    tags: ['divine', 'lightning', 'spear', 'thrust'],
    fx: 'judgementBolt',
  },
];

export const FORM1_SEQ = {
  window: PHASE.window,
  lossOnHit: CHARGE.lossOnHit,
  staticLock: STATUS.staticLockFrames,
};
