/**
 * FORM 2 - THE MACHINE BLESSED BY THE WRONG CREATOR.
 *
 * These names replace the engineered technique names while PROXY OF THE
 * CREATOR is active. The chassis is the same; the authority is not.
 */

import { F2 } from './constants';
import type { MoveDef, ShotDef } from '../../sim/types';

const DIV = ['spear', 'thrust', 'divine', 'lightning'];

export const FORM2_MOVES: MoveDef[] = [
  {
    id: F2.smite,
    name: 'SMITE',
    input: 'J',
    type: 'normal',
    startup: 6,
    active: 4,
    recovery: 10,
    damage: 54,
    chip: 7,
    hitstun: 18,
    blockstun: 13,
    hitstop: 9,
    guardCrush: 11,
    maxHits: 1,
    boxes: [{ x: 18, y: 32, w: 94, h: 22 }],
    vel: [{ from: 6, to: 10, vx: 4.2, vy: 0 }],
    chain: [F2.smite, F2.smiteMedium],
    onHit: 'mk2f2:smiteHit',
    tags: DIV,
    fx: 'divineSmite',
    note: 'Divine punishment. Applies Divine Shock. Counter Hit doubles it.',
  },
  {
    id: F2.smiteMedium,
    name: 'SMITE: MEDIUM ATTUNEMENT',
    input: 'K',
    type: 'normal',
    startup: 10,
    active: 5,
    recovery: 15,
    damage: 82,
    chip: 10,
    hitstun: 20,
    blockstun: 15,
    hitstop: 11,
    guardCrush: 18,
    maxHits: 1,
    boxes: [{ x: 20, y: 30, w: 108, h: 24 }],
    vel: [{ from: 10, to: 16, vx: 9.2, vy: 0 }],
    onActivate: 'mk2f2:smiteMediumStart',
    onHit: 'mk2f2:smiteMediumHit',
    tags: DIV,
    fx: 'divineSmiteMedium',
    note: 'Invokes a larger portion of the borrowed power. Moves farther, strikes harder, discharges again.',
  },
  {
    id: F2.smiteFall,
    name: 'SMITE: SO YOU SHALL FALL',
    input: 'L',
    type: 'special',
    startup: 15,
    active: 6,
    recovery: 22,
    damage: 146,
    chip: 20,
    hitstun: 28,
    blockstun: 18,
    hitstop: 14,
    guardCrush: 40,
    maxHits: 1,
    knockdown: true,
    boxes: [{ x: 22, y: 26, w: 126, h: 30 }],
    vel: [{ from: 15, to: 22, vx: 7.4, vy: 0 }],
    onActivate: 'mk2f2:smiteFallStart',
    onHit: 'mk2f2:smiteFallHit',
    tags: DIV,
    fx: 'divineSmiteFall',
    note: 'A proclamation. Consumes Divine Shock for a violent discharge.',
  },
  {
    id: F2.smiteFallCharged,
    name: 'SMITE: SO YOU SHALL FALL (OVERCHARGED)',
    input: 'L (hold) · 4 Divine Charge',
    type: 'special',
    startup: 18,
    active: 7,
    recovery: 24,
    damage: 196,
    chip: 28,
    hitstun: 30,
    blockstun: 20,
    hitstop: 18,
    guardCrush: 56,
    maxHits: 1,
    knockdown: true,
    boxes: [{ x: 22, y: 24, w: 138, h: 32 }],
    vel: [{ from: 18, to: 26, vx: 9, vy: 0 }],
    cost: { primary: 4 },
    onActivate: 'mk2f2:smiteFallChargedStart',
    onHit: 'mk2f2:smiteFallHit',
    tags: DIV,
    fx: 'divineSmiteFallCharged',
    note: 'The machine dumps a quarter of its store into one thrust.',
  },
  {
    id: F2.ahCreator,
    name: 'AH… CREATOR!',
    input: 'I',
    type: 'movement',
    startup: 4,
    active: 16,
    recovery: 8,
    damage: 0,
    chip: 0,
    hitstun: 0,
    blockstun: 0,
    hitstop: 0,
    guardCrush: 0,
    maxHits: 0,
    boxes: [],
    invuln: [6, 20],
    chain: [
      F2.smite,
      F2.smiteMedium,
      F2.smiteFall,
      F2.smiteFallCharged,
      F2.decapitate,
      F2.judgementCreator,
      F2.creatorRefineMe,
      F2.unrelentingMight,
    ],
    onActivate: 'mk2f2:ahCreatorStart',
    onExpire: 'mk2f2:ahCreatorEnd',
    tags: ['phase', 'divine'],
    fx: 'ahCreator',
    note: 'Lightning displacement through the target. Leaves a Divine Shock trail. Can still Perfect Phase.',
  },
  {
    id: F2.decapitate,
    name: 'I WILL DECAPITATE YOU MYSELF.',
    input: 'U',
    type: 'special',
    startup: 8,
    active: 8,
    recovery: 26,
    damage: 250,
    chip: 30,
    hitstun: 34,
    blockstun: 22,
    hitstop: 20,
    guardCrush: 60,
    maxHits: 1,
    knockdown: true,
    boxes: [{ x: 10, y: 24, w: 112, h: 34 }],
    onActivate: 'mk2f2:decapitateStart',
    onHit: 'mk2f2:decapitateHit',
    tags: DIV,
    fx: 'decapitate',
    note: 'Personal. Closes the distance itself, then finishes the target at point blank range.',
  },
  {
    id: F2.andShowYou,
    name: 'AND SHOW YOU…',
    input: 'O',
    type: 'special',
    startup: 10,
    active: 6,
    recovery: 14,
    damage: 66,
    chip: 9,
    hitstun: 20,
    blockstun: 15,
    hitstop: 12,
    guardCrush: 16,
    maxHits: 1,
    boxes: [{ x: 16, y: 30, w: 100, h: 24 }],
    onActivate: 'mk2f2:andShowYouStart',
    onHit: 'mk2f2:andShowYouHit',
    tags: DIV,
    fx: 'andShowYou',
    note: 'The first half of a sentence. Positions the target inside a formation of divine spears.',
  },
  {
    id: F2.unrelentingMight,
    name: 'MY UNRELENTING MIGHT!',
    input: 'DOWN + O',
    type: 'special',
    startup: 14,
    active: 2,
    recovery: 30,
    damage: 0,
    chip: 0,
    hitstun: 0,
    blockstun: 0,
    hitstop: 0,
    guardCrush: 0,
    maxHits: 0,
    boxes: [],
    onActivate: 'mk2f2:unrelentingMightStart',
    tags: DIV,
    fx: 'myUnrelentingMight',
    note: 'The payoff. Eight divine spear replicas, the storm answers, and nothing gets up.',
  },
  {
    id: F2.judgementCreator,
    name: 'JUDGEMENT: CREATOR',
    input: 'P',
    type: 'special',
    startup: 20,
    active: 4,
    recovery: 26,
    damage: 210,
    chip: 26,
    hitstun: 30,
    blockstun: 20,
    hitstop: 18,
    guardCrush: 62,
    maxHits: 1,
    knockdown: true,
    boxes: [{ x: 0, y: 0, w: 90, h: 150 }],
    onActivate: 'mk2f2:judgementCreatorStart',
    onHit: 'mk2f2:judgementCreatorHit',
    tags: DIV,
    fx: 'judgementCreator',
    note: 'Calls on authority it does not understand. Consumes Divine Shock. The storm visibly responds.',
  },
  {
    id: F2.creatorRefineMe,
    name: 'CREATOR! REFINE ME!',
    input: 'R',
    type: 'super',
    startup: 6,
    active: 1,
    recovery: 132,
    damage: 0,
    chip: 0,
    hitstun: 0,
    blockstun: 0,
    hitstop: 0,
    guardCrush: 0,
    maxHits: 0,
    boxes: [],
    invuln: [1, 8],
    armor: [9, 400],
    onActivate: 'mk2f2:refineStart',
    tags: DIV,
    fx: 'creatorRefineMe',
    note: 'He keeps demanding. The machine rebuilds itself mid-sentence and discharges everything it rebuilt.',
  },
  {
    id: F2.mightOfCreator,
    name: 'THE UNRELENTING MIGHT OF THE CREATOR',
    input: 'R · Attunement 3 · Marked or 3+ Divine Shock',
    type: 'super',
    startup: 6,
    active: 1,
    recovery: 210,
    damage: 0,
    chip: 0,
    hitstun: 0,
    blockstun: 0,
    hitstop: 0,
    guardCrush: 0,
    maxHits: 0,
    boxes: [],
    invuln: [1, 8],
    armor: [9, 600],
    requires: { tier: 3, targetStacks: { heavensMark: 1, divineShock: 3 } },
    onActivate: 'mk2f2:mightStart',
    tags: DIV,
    fx: 'mightOfCreator',
    note: 'A completely transformed ultimate. The whole storm is the weapon.',
  },
  /* strike entities for Form 2 sequences */
  {
    id: F2.seqStrike,
    name: 'DIVINE STRIKE',
    input: '-',
    type: 'finisher',
    startup: 1,
    active: 2,
    recovery: 2,
    damage: 78,
    chip: 10,
    hitstun: 16,
    blockstun: 13,
    hitstop: 8,
    guardCrush: 12,
    maxHits: 1,
    boxes: [],
    onHit: 'mk2f2:seqStrikeHit',
    tags: DIV,
    fx: 'divineSeqStrike',
  },
  {
    id: F2.seqFinal,
    name: 'DIVINE JUDGEMENT',
    input: '-',
    type: 'finisher',
    startup: 1,
    active: 3,
    recovery: 4,
    damage: 260,
    chip: 30,
    hitstun: 34,
    blockstun: 22,
    hitstop: 22,
    guardCrush: 70,
    maxHits: 1,
    knockdown: true,
    boxes: [],
    onHit: 'mk2f2:seqFinalHit',
    tags: DIV,
    fx: 'divineSeqFinal',
  },
];

export const FORM2_SHOTS: ShotDef[] = [
  {
    kind: F2.discharge,
    speed: 9,
    life: 34,
    damage: 34,
    chip: 5,
    hitstun: 16,
    blockstun: 12,
    hitstop: 8,
    guardCrush: 8,
    box: { x: 0, y: 0, w: 64, h: 64 },
    onHit: 'mk2f2:dischargeHit',
    tags: DIV,
    fx: 'divineDischarge',
  },
  {
    kind: F2.divineArc,
    speed: 14,
    life: 30,
    damage: 42,
    chip: 6,
    hitstun: 18,
    blockstun: 13,
    hitstop: 9,
    guardCrush: 10,
    box: { x: 0, y: 0, w: 78, h: 40 },
    onHit: 'mk2f2:dischargeHit',
    tags: DIV,
    fx: 'divineArc',
  },
  {
    kind: F2.phaseTrail,
    speed: 0,
    life: 22,
    damage: 18,
    chip: 2,
    hitstun: 10,
    blockstun: 10,
    hitstop: 4,
    guardCrush: 4,
    box: { x: 0, y: 0, w: 70, h: 90 },
    onHit: 'mk2f2:trailHit',
    tags: DIV,
    fx: 'divineTrail',
  },
  {
    kind: F2.confine,
    speed: 16,
    life: 40,
    damage: 30,
    chip: 4,
    hitstun: 14,
    blockstun: 12,
    hitstop: 7,
    guardCrush: 6,
    box: { x: 0, y: 0, w: 96, h: 26 },
    onHit: 'mk2f2:confineHit',
    tags: DIV,
    fx: 'divineConfine',
  },
  {
    kind: F2.arraySpear,
    speed: 13.5,
    life: 62,
    damage: 36,
    chip: 6,
    hitstun: 16,
    blockstun: 13,
    hitstop: 9,
    guardCrush: 9,
    box: { x: 0, y: 0, w: 122, h: 34 },
    onHit: 'mk2f2:arraySpearHit',
    tags: DIV,
    fx: 'divineArraySpear',
  },
  {
    kind: F2.pillar,
    speed: 0,
    life: 24,
    damage: 64,
    chip: 8,
    hitstun: 18,
    blockstun: 14,
    hitstop: 12,
    guardCrush: 14,
    box: { x: 0, y: 0, w: 70, h: 260 },
    onHit: 'mk2f2:pillarHit',
    tags: DIV,
    fx: 'judgementPillar',
  },
  {
    kind: F2.refineBolt,
    speed: 17,
    life: 46,
    damage: 58,
    chip: 8,
    hitstun: 18,
    blockstun: 14,
    hitstop: 12,
    guardCrush: 12,
    box: { x: 0, y: 0, w: 88, h: 88 },
    onHit: 'mk2f2:refineHit',
    tags: DIV,
    fx: 'refineBolt',
  },
];
